### ISSUE TITLE
es module dist

### ISSUE THREAD

**Issue by LarsDenBakker** [vegarringdal/custom-elements-hmr-polyfill#14]
I'm evaluating if it is possible to combine this with https://github.com/systemjs/systemjs/pull/2014 to enable hot reloading workflows in https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server. Unfortunately, you're only shipping commonjs at the moment.

Could you make a single file es module output, so that it can be run in the browser?

**Comment by kyr0** [comment]
Hi Lars,

nice to see you trying to integrate this with `es-dev-server`. We've just finished the `beta.1` moments ago. This release brings a lot of changes and improvements. Please check it out. @vegarringdal is working on es module output now and we'll get back to you as soon as we have it up and running.

Thanks and best,
Aron

**Comment by vegarringdal** [comment]
@LarsDenBakker 
FYI

Started here:
https://github.com/vegarringdal/custom-elements-hmr-polyfill/pull/15

Added more outputs on build, including "single file es module" unless Ive messed up something.
Never made singlefile before, so I need to test tomorrow if Ive broken something/it works.
If anyone can clone, run `npm install` & `npm run build` and help test it then that would be great.

**Comment by kyr0** [comment]
@LarsDenBakker 
We've finished our work on the new build system and released `custom-elements-hmr-polyfill@1.0.0-beta.2` including SystemJS support.

Please have a look at: https://github.com/vegarringdal/custom-elements-hmr-polyfill#distribution-formats

Thanks and best,
Aron

**Comment by kyr0** [comment]
@LarsDenBakker 
In case you prefer file downloads: https://github.com/vegarringdal/custom-elements-hmr-polyfill/releases/tag/1.0.0-beta.2

**Comment by LarsDenBakker** [comment]
Thanks, it's working for me. Right now the `module` field is pointing to the unbundled files, probably would be best to point to the bundled instead. I'm a fan of shipping unbundled code, but for focused libs/polyfills it's easier to handle when it's just one file.

**Comment by LarsDenBakker** [comment]
I'm creating issues for things I'm finding, I realize it's still in beta so it's not any criticism at all :) It's working out pretty well so far actually!

**Comment by vegarringdal** [comment]
@LarsDenBakker 
I think its great you create issues. It will help us make it better.
Ive started looking at the issues, but not home atm so not much I can do 😁
How would you mostly use it? 

I usually just use ReflowStrategy.NONE and call the renderInnerHtml before I apply polyfill.
No dom traversal then.

**Comment by vegarringdal** [comment]
I see Ive closed this one a little early.

> Thanks, it's working for me. Right now the module field is pointing to the unbundled files, probably would be best to point to the bundled instead. I'm a fan of shipping unbundled code, but for focused libs/polyfills it's easier to handle when it's just one file.

Best would be to use this then:
`"module": "dist/custom-elements-hmr-pollyfill.mjs",`

**Comment by kyr0** [comment]
@vegarringdal Yes, but there has been a problem with fuse-box. Has that been resolved in the meantime?

**Comment by vegarringdal** [comment]
Looks like it works fine now.
Maybe I just messed up last time, it was late 😂 
I manually edited the package.json in one proecjt and deleted every other file under dist. disabled cache and enabled vendor sourcemaps. and it used the mjs file


![image](https://user-images.githubusercontent.com/2901416/64491785-933c1500-d26c-11e9-8071-9016110ce663.png)

**Comment by vegarringdal** [comment]
btw, I did a PR yesterday on fusebox too, so next release "ts:main" gets precedence over "module" in fusebox.
So we could add `"ts:main": "src/package/index.ts"` too...

**Comment by vegarringdal** [comment]
@LarsDenBakker 

Hi Ive been doing some maintance on the repo.
Adding tests/eslint etc.

Have you been using it btw?
Was thinking about changing the module to the .mjs file too.
Will need to go up to 2.0.0 when I do.

Anything else you can think about I should fix at the same time?

**Comment by vegarringdal** [comment]
no response, so closing this..
