### ISSUE TITLE
replaceByClone does not work with shadow dom

### ISSUE THREAD

**Issue by LarsDenBakker** [vegarringdal/custom-elements-hmr-polyfill#18]
`node.childNodes` does not return elements within a shadow root. 

Replacing:
```js
visit(childNode, elementNames);
```
With:
```js
visit(childNode, elementNames);
if (childNode.shadowRoot){
  visit(childNode.shadowRoot, elementNames);
}
```

seems to be working, but I'll do some further testing. However, since you're already wrapping the base class and have access to the connected/disconnected callbacks probably it would be better to maintain a list of all the instances for a given element name. That way you don't need to walk the entire dom tree for each change.

**Comment by kyr0** [comment]
Thank you again, good point. There is one limitation I could think of: Closed mode shadow DOM. This wouldn't be accessible from without. We probably need to refactor this to tun the shadowDOM reflow inside of the web component. On the other hand, when a web component element is newly constructed, it shadow DOM should be completely re-constructed and thus be reflowed anyway?

> That way you don't need to walk the entire dom tree for each change.

Yes, that is an optimization I had in mind too :)

**Comment by vegarringdal** [comment]
Using ReflowStrategy.NONE and calling renderInnerHtml () before the pollyfill will also solve this. But the more options we have the better. Hard to say how everyone will use it.

**Comment by kyr0** [comment]
We've decided to remove the `CloneAndReplace` strategy as it has shown to be quite unstable and complex. Please try the new `custom-elements-hmr-polyfill@1.0.0-beta.3`
