### ISSUE TITLE
Redefiniton causes state to be lost

### ISSUE THREAD

**Issue by LarsDenBakker** [vegarringdal/custom-elements-hmr-polyfill#19]
Redefining a custom element causes any state (javascript properties) to be lost. This can actually be a good thing when you're changing the way an element works, but it's a problem when the properties are set by a parent element. The parent element doesn't know that it needs to set the properties again, so the replaced custom element will render with an incorrect state. I'm seeing this for example with [lit-element](https://github.com/Polymer/lit-element).

Unfortunately, there isn't a standard way for custom elements to define their state/properties, and I'm not sure if a naive Object.assign(newInstance, oldInstance) will work out. Perhaps there needs to be a hook, so that this can be implemented per web component library.

**Comment by kyr0** [comment]
We could at least remember the attributes that were set before replace and restore them after replace. This will also fix the other issue where you expected the attribute change listener to be called also for the initial attribute definition.

**Comment by kyr0** [comment]
Especially when adding the instance cache feature for faster reflow lookups, we could also remember the current state of attributes there and reply them on reflow.

**Comment by LarsDenBakker** [comment]
A web component's state isn't only stored in attributes. Depending on the rendering library that's being used in the application, a lot is stored in properties and event listeners. Reconstructing a child won't restore those.

**Comment by vegarringdal** [comment]
Hmr restoring state sounds like something that can go very bad. Rerendering app will be a lot safer. How will you know if the properties you try and restore is even valid anymore and not a old instance of something the hmr have replaced ?

**Comment by LarsDenBakker** [comment]
You're right it's quite complex. I was under the impression this is how it works with React hot reloading. In some ways it's easier for React, since they're in full control.

**Comment by vegarringdal** [comment]
Most react app uses store to get state when created I guess (never used react). If you always restore state in constructor/connectedCallback (only events in the last one). And make sure controller/parent custom elements get replaced when a hmr event happens it work very well.
This is why I just restore entire app everytime by using the strategy.NONE and call renderInnerHtml before the pollyfill

**Comment by vegarringdal** [comment]
@kyr0 
I feel calling this a bug is wrong, better to label it a "discussion".

We could do what we have talked about earlier. Add a general how to write HMR'able web components.

**constructor**
* never register any form of event listeners here, connectedCallback/disconnectedCallback might never get called.
* good place to restore state


**connectedCallback**
* if you register eventlistenres you have to remove them in disconnectedCallback.
* always check `isConnected`. Parent element might replace its innerHTML before you connectedCallback is called.

**HMR event.**
* Some modules might not handle HMR very well if you call them again. You might need to put in a check for this.

**Comment by LarsDenBakker** [comment]
Those are general good practices for handling element connecting/disconnecting anyway :)

I agree this is just a discussion/exploration, mostly regarding replacing an element instance rather than re-rendering the entire DOM tree. I'm really interested in trying to make this work.

We should be able to write an individual component in a way that it can handle reloading, but I'm not sure how we can take care of the expectations of a parent element.

For example, given this element:

```js
class Parent extends HTMLElement {
  connectedCallback() {
    const child = document.createElement("my-child");
    child.message = "hello world";
    child.addEventListener("foo", () => {
      console.log('foo event fired');
    });
    this.appendChild(child);
 }
}
```

If we hot reload `my-child`, the event listener and property set by the `Parent` element are gone breaking the application. 

This is a really common pattern with `lit-html` / `lit-element`:

```js
class Parent extends LitElement {
  render() {
    return html`
      <my-child .message=${this.message} @foo=${this._onFooFired}></my-child>
    `;
  }
}
```

**Comment by vegarringdal** [comment]
> I agree this is just a discussion/exploration, mostly regarding replacing an element instance rather than re-rendering the entire DOM tree. I'm really interested in trying to make this work.

I changed it to enhancement.

> We should be able to write an individual component in a way that it can handle reloading, but I'm not sure how we can take care of the expectations of a parent element.

Yes, its really hard to say what parent element does, thats why Im a fan of rerender entire page.
I use lit.html too and its really fast. You usually wont know if it just rerendered entire page or part if it.

Great if you find a good way to handle hot reloading. But I think it would best to test with a app to see if you really get enough lag to use much time on it 😄 
But if you plan to use time on this then the custom element should somehow register if they are controllers. Like a router that dynamically load other components need to rerender to load and update instances of child elements. Or custom element that passes data down to children by properties in connectedCallback.


> hmr.ts
```
import { applyPolyfill, ReflowStrategy, rerenderInnerHTML } from 'custom-elements-hmr-polyfill';

//cleanup
// you might want to clean up modules that wont handle restart here...

// call rerender
rerenderInnerHTML();

// apply pollyfil
applyPolyfill(ReflowStrategy.NONE, 0, (elementName:string) => {
    console.log("updated", elementName)
});
```

**Comment by kyr0** [comment]
In `custom-elements-hmr-polyfill@1.0.0-beta.3`, attributes are set (also initially).

**Comment by vegarringdal** [comment]
@LarsDenBakker 

Did you make any scripts/plugins that reused dom in any way with lit-element ?
Or did end up rerendering ? :-)

**Comment by LarsDenBakker** [comment]
Not yet, doing the full re-render for now :)

**Comment by vegarringdal** [comment]
@LarsDenBakker 

Did you end up making anything with this polyfill ?
Would be nice to know about if you did. 😄

**Comment by LarsDenBakker** [comment]
Its still in a draft PR https://github.com/open-wc/open-wc/pull/788 but I havent had time to finish it
