### ISSUE TITLE
references to static members are lost

### ISSUE THREAD

**Issue by LarsDenBakker** [vegarringdal/custom-elements-hmr-polyfill#22]
After the proxy is set up, references to static members through `this.constructor` are lost. This causes a problem with for example LitElement, which stores styles as a static field on the constructor.

You can see a simple example here: https://codesandbox.io/embed/custom-elements-hmr-polyfill-f7f81 

If you change `static foo = "foo"` to `static foo = "bar"` it does not work.

I tried to fix this myself, but I'm not too familiar with proxies.

**Comment by vegarringdal** [comment]
Thank you @LarsDenBakker for supplying the codesandbox.

Ill have a look at it now 👍

**Comment by kyr0** [comment]
@LarsDenBakker Please update to `custom-elements-hmr-polyfill@1.0.0-beta.5`

**Comment by LarsDenBakker** [comment]
Thanks!
