### ISSUE TITLE
Question: guaranteed to be deps-free?

### ISSUE THREAD

**Issue by Leedehai** [vegarringdal/custom-elements-hmr-polyfill#29]
Curious, is "dependency-free" a long-term goal of this project? Currently it has 0 dependency (excluding devDependencies).

**Comment by vegarringdal** [comment]
I dont see any reason to add any dependencies.
I guess as long as it works with my weird little project [here](https://github.com/simple-html/simple-html) it will stay dep free 😄 


Any special reason for the question ?

**Comment by vegarringdal** [comment]
@kyr0 
I guess you do not have any need for adding any deps either ?

**Comment by kyr0** [comment]
I guess I'm very proud of software being dependency free 👍 It's a goal for me. My whole [web development framework](https://github.com/springtype-org/springtype/tree/master-v2) is dependency free :D

**Comment by vegarringdal** [comment]
Good. 😁
