### ISSUE TITLE
Side-effect free?

### ISSUE THREAD

**Issue by Leedehai** [vegarringdal/custom-elements-hmr-polyfill#30]
Hi, I'm wondering if side-effect-free is a long term goal of this polyfill? In other words, as long as I do not call any exported function like `applyPolyfill()`, CustomElementsRegistry, or any other browser-provided objects, will not be overridden.

I scanned through the code, and it's side-effect free at the moment. The reason for this question is I don't want this polyfill, which is intended to polyfill dev build with HMR, to be applied to the production build.

Thanks!

**Comment by vegarringdal** [comment]
@Leedehai 

> Hi, I'm wondering if side-effect-free is a long term goal of this polyfill? In other words, as long as I do not call any exported function like applyPolyfill(), CustomElementsRegistry, or any other browser-provided objects, will not be overridden.

Yes, I have no plans to add any automatic override by just importing it.
Better to leave it up to the user when someone wants to do this and how.

**Comment by Leedehai** [comment]
Thanks!
