### ISSUE TITLE
Not working with webcomponentsjs polyfills

### ISSUE THREAD

**Issue by jimsimon** [vegarringdal/custom-elements-hmr-polyfill#34]
I'm playing with some react and web components bridging and I can't seem to get this polyfill to work with elements created using lit-element.

See https://codesandbox.io/s/custom-elements-hmr-polyfill-r381h for an example.

Whenever I make a change in the render function I end up getting the "element has already been used with this registry" error.  Any idea what I'm doing wrong?

**Comment by jimsimon** [comment]
It appears this has to do with loading the webcomponentsjs polyfills.  If I load them then this polyfill fails, but if I don't then it works.  I'm still testing, but I suspect it's possibly a load order issue.

**Comment by jimsimon** [comment]
Okay, it was definitely a load order issue without how I was loading the webcomponentsjs polyfills.  Please disregard!

**Comment by jimsimon** [comment]
Okay, nevermind again, there's definitely an issue when loading polyfills.  See: https://codesandbox.io/s/custom-elements-hmr-polyfill-1eswo?file=/src/index.ts

**Comment by vegarringdal** [comment]
Ill have a look later today or tomorrow.
Plan to add some test within this month too using jest/jsdom.

But its only bugging when using web component polyfill ?
Are you using newest chrome /FF? 

Last question. Why are you using webcomponent polyfill during development ? All new browser support stand web component now (I think 🙈)

**Comment by jimsimon** [comment]
I'm on the latest version of Chrome.

I actually started playing around from the lit-element example in their docs which includes the polyfills by default, so it was mostly an accident.  That being said, I'm doing some R&D for work and we still have to support IE11 for a11y purposes.  It wouldn't be unusual for someone to develop/test something in IE11 with the polyfills loaded.

**Comment by vegarringdal** [comment]
Yes but for the **custom-elements-hmr-polyfill** to work you need proxy. So it wont work in IE11.

I tried lit-element a while back. But ended up just using lit-html with some helper functions around it.
Lit-html is fun to use, and fast.
Plan is to try out lighterhtml too. Just havent gotten around yet since what I have works.

**Comment by vegarringdal** [comment]
Hi
Tried the sample.
You need to load the polyfill before everything else.

Have look at this:
https://codesandbox.io/s/custom-elements-hmr-polyfill-je0sg?file=/src/index.ts

**Comment by vegarringdal** [comment]
Also best way to use it is to have 1 root-app component and just replace this one on the hmr event

**Comment by jimsimon** [comment]
Your updated example doesn't appear to be loading the webcomponentsjs polyfills.  They're commented out in index.html and no longer referenced in any of the TS files.

**Comment by vegarringdal** [comment]
ops, sorry.
Let me have a quick check again.
Been busy adding jest/eslint etc to the repo last hour :-)

**Comment by vegarringdal** [comment]
@jimsimon 
From what I can tell those polyfills messes up the hmr polyfill.
Dont think there is very much I can do about it.

Normally you would not try and load a polyfill like that unless its a missing feature. Atm it looks like it overrides customElement define by default and stopping me from doing it.

May this works better:
https://github.com/ungap/custom-elements-builtin


@kyr0 
U there ?
Did you test all these ? Did do anything special to get it to work ?
Else I might just remove this part.

![image](https://user-images.githubusercontent.com/2901416/79165523-94758780-7de3-11ea-95a4-845a3e0b31f3.png)

**Comment by vegarringdal** [comment]
Have you tiried it in a browser that does not have custom elements?
Maybe it works.. That error might not be a issue there, since there wont be CustomElementRegistry that will throw that error.

**Comment by vegarringdal** [comment]
@jimsimon 

Have a look at this
Used another polyfill and run it in edge...
Its a start, Ill remove pollyfill part of the readme.

https://github.com/vegarringdal/custom-elements-hmr-polyfill-webpack

**Comment by vegarringdal** [comment]
@jimsimon 
Did you get to try it in edge?

btw:
Updated the readme file. Removed references to the polyfills.
So closing this for now

**Comment by jimsimon** [comment]
I haven't tried it yet as I've been busy with other work stuff.  I'll try to swing back to this today.

**Comment by vegarringdal** [comment]
ok.
Take your time :-)
If you know more about webpack then me. Then feel free to make a PR to that repo. 👍
