### ISSUE TITLE
npm installed elements breaks

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/custom-elements-hmr-polyfill#39]
Might need to have this a option part:
https://github.com/vegarringdal/custom-elements-hmr-polyfill/blob/master/src/package/polyfill/constructInstance.ts#L18-L39

Is it only polymer elements I break?

**Comment by vegarringdal** [comment]
@douglascvas

Did some more testing, looks like everything works fine as long as you dont reimport custom elements.
Sample:  (yes I have no clue how webpack works...)
https://github.com/vegarringdal/custom-elements-hmr-polyfill-webpack

**Comment by vegarringdal** [comment]
So basicly, custom elements you have installed not making/editing you load before the pollyfill..

**Comment by jorenbroekema** [comment]
Hey @vegarringdal  I installed this today and I am actually facing a problem indeed for custom elements that are defined to the registry from node_modules. Seems like my custom element is not defined properly when the polyfill is applied beforehand. 

To reproduce:

Install the custom element, the polyfill, and a dev server which can resolve bare imports (using es-dev-server here)
```
yarn add es-dev-server @lion/dialog custom-elements-hmr-polyfill
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script type="module">
      import { applyPolyfill } from 'custom-elements-hmr-polyfill';

      applyPolyfill();

      async function loadDialog() {
        await import('@lion/dialog/lion-dialog.js');
      }
      loadDialog();
    </script>
  </head>
  <body>
    <lion-dialog>
      <button slot="invoker">Invoker</button>
      <div slot="content">Content</div>
    </lion-dialog>
  </body>
</html>
```

```
yarn es-dev-server --node-resolve --open --watch
```

See error in console, which happens because the dialog component shadow dom is not rendered.
If the JS code inside index.html is changed to load the dialog before applying the polyfill, things are working just fine:

```js
import '@lion/dialog/lion-dialog.js';
import { applyPolyfill } from 'custom-elements-hmr-polyfill';

applyPolyfill();
```

Hopefully this will help you debug the problem further :) let me know if I can do anything to help out, but I'm not very familiar with the implementation code of this polyfill 😅

**Comment by jorenbroekema** [comment]
I figured out that it's working okay with HTMLElement , but not with LitElement https://lit-element.polymer-project.org/

It doesn't work regardless of whether the component comes from node_modules or from a local folder. Which would be weird if it were otherwise.

Repro:
index.js (yarn add lit-element to install lit-element)
```js
import { html, LitElement } from 'lit-element';

class MyComponent extends LitElement {
  render() {
    return html`<h1>Hello</h1>`;
  }
}
customElements.define('my-component', MyComponent);
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script type="module">
      import { applyPolyfill } from 'custom-elements-hmr-polyfill';
      // import './index.js'; // <-- this one works because it will load and define the my-component before applying the polyfill

      applyPolyfill();

      import('./index.js'); // breaks :(
    </script>
  </head>
  <body>
    <my-component></my-component>
  </body>
</html>
```

**Comment by vegarringdal** [comment]
@jorenbroekema

Hi, I havent really had time to figure it out completly
Have you tried the master branch ?
I added a option to the deep patching here. (default will be "no")
https://github.com/vegarringdal/custom-elements-hmr-polyfill/blob/master/src/package/polyfill/constructInstance.ts#L36-L40
Looks like that helps lit-element from failing..

On standard class or mixing this should work fine on the little testing Ive done..
But maybe lit-element sets some variables localy in the modules making it all fail somehow :-)
If thats the case then its really nothing I can do...
Hopefully Ive just missed something

Would have been useful to reproduce issues with local classes and HTMLElement.

I know that polly for observedAttributes using MutationObserver can create a delay, or atleast I think it the issue on some external libs Ive tried. Also Ive seen I missing 1 more argument by default, attribute namespace..

**Comment by vegarringdal** [comment]
hm, I think I see why now

When Im been making dummy element with decorators etc Ive main user class is extending HTMLElement.
Then I have a base class extending that class, so my base class extends users class, this is why I needed more patching.
I need to test a little more today, but my path on 1.0.1 might have broken more then it did good for many...

**Comment by vegarringdal** [comment]
@jorenbroekema 

published version 1.0.3

Add this before pollyfill:
`(window as any).HMR_SKIP_DEEP_PATCH = true`

**Comment by vegarringdal** [comment]
@jorenbroekema did you try version 1.0.3

**Comment by jorenbroekema** [comment]
Hey, that's great, I'll be able to test it tomorrow afternoon :) got a bit caught up in other work so couldn't try today / this weekend. Thanks for releasing what may be a fix for my problem 🤗 I'll let you know!

**Comment by vegarringdal** [comment]
Great.

From what I can tell lit-element just does not like if I mess with the prototype of litElement, or the other classes they have in there..
But users class is whats passed into customElement, so we really dont need to patch deeper.

I only use `lit-html` and have own wrappers around it, so never seen these issues.
https://github.com/simple-html/simple-html, weird little project 😂 

See some vaadin elements dont like me yet, fixed a lot, date dropdown looses its content context, maybe its attributecallback doing something wrong.. need to check this next days/end of week
Maybe shadowdom have something I dont know about, never use shadowdom..

**Comment by jorenbroekema** [comment]
Upgrading to 1.0.3 and adding `window.HMR_SKIP_DEEP_PATCH = true;` solved my issue, thanks!

**Comment by vegarringdal** [comment]
@jorenbroekema great 👍

Ill try and get rid of the option by checking type of class or something later, just to busy atm.
