### ISSUE TITLE
whitelist / blacklist

### ISSUE THREAD

**Issue by yorrd** [vegarringdal/custom-elements-hmr-polyfill#41]
`@material/mwc-tab` and `@material/mwc-tab-bar` dont seem to work with these components. 

Suggestion: is it possible to add a whitelist / blacklist? I don't think we'll ever need those components to HMR since they are dependencies we just import and use. That would save us some trouble because then we're good to go when we get it to work with only our stuff. 

Thanks!

**Comment by vegarringdal** [comment]
Have you tried adding the option I added in 1.0.3
`(window as any).HMR_SKIP_DEEP_PATCH = true``

Isnt it possible to load the components before the pollyfill ?
We could prob add some skip option, but some libs Ive seen load a lot of small components, so loading them before would be a lot simpler..
Even the datagrid Ive made loads like 15-20 internal components 😂

**Comment by yorrd** [comment]
true. The option doens't do anything for me, but I work around the issue this way now: 

```
export function polyfillWebcomponents(skipNodePackages: string[] = []) {
  // make sure they're loaded before the polyfill to work around them not working with it
  skipNodePackages.forEach(pack => require(pack));

  applyPolyfill(ReflowStrategy.NONE, undefined, (name, implementation, options) => {
    // our side effect that we catch in components
    hmr$.next({ name, implementation });
  });
}
```

**Comment by vegarringdal** [comment]
Marked it as info
Others could just add the function if they need it 👍 
What does the `hmr$.next` do ?

**Comment by yorrd** [comment]
`hmr$.next` takes the hmr update data you're passing to the callback and pushes it into a rxjs subject that we distribute across the application to handle side effects and implement reflow logic (basically triggering our state management system again in most cases) :)

**Comment by vegarringdal** [comment]
ok.
I dont know much about state management.
Have just used a little global state object the mini apps Ive done in my `@simple-html` wrapper lib I have around lit-html.
It takes care of saving state for me.
https://codesandbox.io/s/modest-kapitsa-tpclh?file=/src/elements/sample-no1.ts
😂 
codesandbox isnt always stable when I use the node version, but its very cool we can run node and for free. SO might need to hit refresh in the viewport/content part

**Comment by yorrd** [comment]
looks smart! the library is not public on github atm right? Was going to take a look at simple-html but no chance :P we pretty much use rxjs for state management and have made decorators to facilitate passing them to the render method. With rxjs we can control every aspect of rerendering just like in your 4th sample. I think it's quite cool that you manage to do state without a superclass. We have one and it's not always helpful :D

**Comment by vegarringdal** [comment]
https://github.com/simple-html/simple-html

hobby project :-)
but datasource & grid is getting better... migth be weird for others

**Comment by yorrd** [comment]
thanks, definitely taking a look!

**Comment by vegarringdal** [comment]
Great, just dont get scared if some parts are weird.
Like I said, hobby project Im working on when I have time and for fun :-)

**Comment by douglascvas** [comment]
Hey @vegarringdal, where can I see the code where you have the `HMR_SKIP_DEEP_PATCH` flag? I can't find it in master.

**Comment by vegarringdal** [comment]
@douglascvas 
thanks for asking.
I had forgot to push the updates..
You will find it here.
https://github.com/vegarringdal/custom-elements-hmr-polyfill/blob/master/src/package/polyfill/constructInstance.ts#L37

Sorry
