### ISSUE TITLE
Polyfills and cross-browser tests + matrix

### ISSUE THREAD

**Issue by kyr0** [vegarringdal/custom-elements-hmr-polyfill#5]
I think we should setup some CI and execute cross-browser tests like with:

[BrowserStack automation](https://www.browserstack.com/open-source?ref=pricing)

So we can show a matrix which browsers / versions are supported.

Also, we should include auto-applying polyfills for and Proxy, customElements API, so whenever support is not given, it adds automatically. As a result we could show another matrix of what browsers / versions are supported when polyfills are provided.

**Comment by kyr0** [comment]
I'd recommend using:

[TestCafe with BrowserStack provider](https://github.com/DevExpress/testcafe-browser-provider-browserstack)

I can make a PR soon.

TestCafe is just amazing -- also we can run tests locally super-fast and easy :)

**Comment by vegarringdal** [comment]
Sure, if you can set it up easly then go for it.
Nothing better then tests stopping me from breaking anything 😂

**Comment by kyr0** [comment]
Actually we could create another codesandbox with common polyfills. 

Then we could let TestCafe target: https://4vd3o.csb.app/
And the other instance with polyfills.

Finally I'll write the TestCafé tests and we have a 100% polyfill including e2e tests?

**Comment by vegarringdal** [comment]
Sure.
But again it is s development tool. Support for outdated browser doesnt matter very much does it?
But having them test will be great. Never used testcafe so will be nice to learn more about it.

**Comment by vegarringdal** [comment]
Added tests so it have something
#37
Closing this for now
