### ISSUE TITLE
npm release and programmatic API hooks

### ISSUE THREAD

**Issue by kyr0** [vegarringdal/custom-elements-hmr-polyfill#6]
I think it would be nice if we'd have programmatic API hooks so that a developer of an HMR library can register a callback that is called after a Web Component mutated: 

    import {registerOnUpdate, applyPolyfill} from "@vegarringdal/customElements-hmr"; 
    import {someVirtualDOMAPI} from "@some-org/some-framework";

    // somewhere in bootstrap of the app
    applyPolyfill(); 

    // some HMR lib we have no control over
    registerOnUpdate((elementTagName: string) => {
        
        // re-render elements which have changed
        someVirtualDOMAPI.clearAndRenderByTagName(elementTagName);
    });

Something like that.

`someVirtualDOMAPI.clearAndRenderByTagName` could be application code or framework code, depending on the integration.

Finally, it would be nice to release this polyfill and it's API as an npm package, so everybody can use it. 

Fuse-box could require it per default -- but -- if the developer has no direct control over what to do after Web Component code change, the application might break (in case we would basically throw away and re-apply the whole <body> content like we do atm)

**Comment by vegarringdal** [comment]
Yes, good idea.

If we release it we can call it just `customelements-hmr` or `custom-element-hmr`.
This way its easy to remember.

Ill reorginize the repo so it will be easy to publish and have samples running when developing
Ill continue on the dev repo.

Ill send a update when Im done.
